spring:
  kafka:
    bootstrap-servers: kafka:9092
    topic: my-topic4
    listener:
      ack-mode: manual
    consumer:
      properties:
        spring.json.trusted.packages: com.davdavtyan.smsproject.model
      group-id: my-consumer-group3
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      properties:
        spring.json.trusted.packages: com.davdavtyan.smsproject.model
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  elasticsearch:
    rest:
      uris: http://localhost:9200
    properties:
      spring.data.elasticsearch.cluster-name: my-cluster
      spring.data.elasticsearch.cluster-nodes: localhost:9300
  kibana:
    rest:
      uris: http://localhost:5601
    properties:
spring.data.mongodb:
  uri: mongodb://localhost:27017/my-database
